#==========================================================
# OptiServe用Configファイル
# 
# ChangeLog:
#   v1.0.0 (2025-08-06)
#   - 新規作成（smds_core用設定をベース）
#   v1.1.0 (2025-08-28)  
#   - smds_core依存を削除、標準loggingに移行
#   - logging設定は不要になったためコメントアウト
#==========================================================

# 以下の設定は現在未使用（smds_core.Logger用の設定だったため）
# 標準loggingの設定は src/main.py で直接設定済み

# logging:
#   LOGPATH: "./log"
#   LOGNAME: "OptiServe"
#   LOGFILTER: "DEBUG"
#   LOGMAXSIZE: 4194304
#   LOGBACKUPCOUNT: 5
#   ORIGINAL_MSG: True

#----------------------------------------------------------
# データベース設定（未使用）
# Note:
#   - データベース接続は src/database.py で path_config により自動設定
#----------------------------------------------------------
# database:
#   uri: "sqlite:///poc_optigate.db"
#   echo: False

# このファイルは将来的な設定拡張のために保持