@startuml
'-------------------------------------------
'Table Name  : mst_medical_facility
'Description : 医療機関マスタ（公開データ）
'
'[ChangeLog]

'  v1.0.0 (2025-06-27)
'  - [H.Miyazawa] OptiServe用のデータベース設計

'  v1.1.0 (2025-07-10)
'  - [H.Miyazawa] インデックス情報を追加

'  v1.2.0 (2025-08-13)
'  - [H.Miyazawa] 登録、更新のユーザーIDを追加

'  v1.3.0 (2025-08-22)
'  - [H.Miyazawa] ユーザーIDをintegerからtextに変更。

'[Note]
'  - 2025-08-22 : generate_dbdesign_artifacts.pyによる自動生成
'-------------------------------------------
hide circle

entity "mst_medical_facility" as e01 {
  * medical_id : Integer

  --
  * medical_name : Text
    address_postal_code : Text
    address_prefecture : Text
    address_city : Text
    address_line1 : Text
    address_line2 : Text
    phone_number : Text
  * reg_user_id : Text
  * regdate : DateTime
  * update_user_id : Text
  * lastupdate : DateTime

}
@enduml