'----------------------------------------------------------
' ユースケース図
'    OptiServe
'    医療機関ユーザーユースケース図
' 修正の履歴
'    2025-03-04 H.Miyazawa 新規作成
'----------------------------------------------------------
@startuml
left to right direction
actor HpUser
actor Admin
actor Dealer
package "システム外" {
HpUser -- (アカウント追加の依頼)
(アカウント追加の依頼) --> Admin 
(アカウント追加の依頼) -- Dealer
Dealer --> Admin : ディーラー経由で\n依頼を行なう
HpUser -- (アカウント停止の依頼)
(アカウント停止の依頼) --> Admin
(アカウント停止の依頼) -- Dealer
}
package "OptiServe" {
HpUser -- (基本情報のメンテナンス)
HpUser -- (医療機関情報のアップロード)
HpUser -- (レポートのダウンロード)
HpUser -- (機器台帳のメンテナンス)
HpUser -- (出力対象の機器分類選択)
HpUser -- (部門と診療科の紐付け) : (Phase2) 
HpUser -- (ポイント運用) : (Phanse2)
(基本情報のメンテナンス) --> (通知先メールアドレスの登録) : <<include>>
(基本情報のメンテナンス) --> (パスワードの変更) : <<include>>
(基本情報のメンテナンス) --> (ディーラーの登録) : <<include>>
(ディーラーの登録) --> Dealer : 通知
(機器台帳のメンテナンス) --> (集計対象機器の選択) : <<include>>
(機器台帳のメンテナンス) --> (機器と機器分類の紐付け) : <<include>>
(ポイント運用) --> (ポイントの残高確認) : <<include>>
(ポイント運用) --> (ポイントの利用) : <<include>>
}
@enduml