'----------------------------------------------------------
' ユースケース図
'    OptiServe
'    管理者アカウントのユースケース
' 修正の履歴
'    2025-03-04 H.Miyazawa 新規作成
'----------------------------------------------------------
@startuml
left to right direction
actor Admin
package "OptiServe" {
Admin -- (医療機関アカウントの管理)
Admin -- (ディーラーアカウントの管理)
Admin -- (メーカーアカウントの管理) : (Phase2)
(医療機関アカウントの管理) ..> (アカウントの追加) : <<include>>
(医療機関アカウントの管理) ..> (アカウントの無効化) : <<include>>
(医療機関アカウントの管理) ..> (レポート出力ランク数設定) : <<include>>
(医療機関アカウントの管理) ..> (ポイント管理) : <<include>> (Phase2)
(ディーラーアカウントの管理) ..> (アカウントの追加) : <<include>>
(ディーラーアカウントの管理) ..> (アカウントの無効化) : <<include>>
(ディーラーアカウントの管理) ..> (医療機関との関連・権限付与) : <<include>>
(メーカーアカウントの管理) ..> (アカウントの追加) : <<include>>
(メーカーアカウントの管理) ..> (アカウントの無効化) : <<include>>
(メーカーアカウントの管理) ..> (Tableau閲覧医療機関数設定) : <<include>>
(メーカーアカウントの管理) ..> (売掛管理) : <<include>>
}
@enduml